/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'andrii.omelchuk' at '3/21/17 9:44 AM' with Gradle 2.14.1
 *
 * @author andrii.omelchuk, @date 3/21/17 9:44 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
